version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - elknet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    container_name: kibana
    hostname: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      TZ: America/Guayaquil
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - elknet

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    container_name: logstash
    hostname: logstash
    ports:
      - 5044:5044
    depends_on:  
      - kibana 
    networks: 
      - elknet

networks:
  elknet:
